from registries.standards.adapter_standards import (
    daily, weekly, monthly, annually,
    intraday_1min, intraday_5min, intraday_10min, intraday_30min, intraday_1hour
)

# ---- Ideal number of DataFrames to pass per indicator ----
# Single‑instrument transforms -> 1; pairwise/statistical cross‑series -> 2.
strategy_ideal_number_dataframes = {
    # Volume
    "chaikin_ad_line": 1,
    "ADOSC": 1,

    # Trend & Directional
    "ADX": 1,
    "ADXR": 1,
    "DX": 1,
    "MINUS_DI": 1,
    "PLUS_DI": 1,
    "MINUS_DM": 1,
    "PLUS_DM": 1,

    # Oscillators / Momentum
    "APO": 1,
    "AROON": 1,
    "AROONOSC": 1,
    "CMO": 1,
    "CCI": 1,
    "MOM": 1,
    "PPO": 1,
    "ROC": 1,
    "ROCP": 1,
    "ROCR": 1,
    "ROCR100": 1,
    "RSI": 1,
    "STOCH": 1,
    "STOCHF": 1,
    "STOCHRSI": 1,
    "ULTOSC": 1,
    "WILLR": 1,
    "BOP": 1,

    # Volatility / Bands / Ranges
    "ATR": 1,
    "NATR": 1,
    "TRANGE": 1,
    "BBANDS": 1,

    # MAs and MA‑derived
    "SMA": 1,
    "EMA": 1,
    "WMA": 1,
    "DEMA": 1,
    "TEMA": 1,
    "TRIMA": 1,
    "KAMA": 1,
    "T3": 1,
    "MA": 1,
    "MACD": 1,
    "MACDEXT": 1,
    "MACDFIX": 1,
    "TRIX": 1,
    "MAMA": 1,
    "MIDPOINT": 1,

    # Price transforms
    "AVGPRICE": 1,
    "MEDPRICE": 1,
    "MIDPRICE": 1,
    "TYPPRICE": 1,
    "WCLPRICE": 1,

    # Statistics / regressions
    "BETA": 2,           # asset + benchmark (pairwise)
    "CORREL": 2,         # pairwise correlation
    "LINEARREG": 1,
    "LINEARREG_ANGLE": 1,
    "LINEARREG_INTERCEPT": 1,
    "LINEARREG_SLOPE": 1,
    "STDDEV": 1,
    "VAR": 1,
    "TSF": 1,
    "SUM": 1,
    "MAX": 1,
    "MIN": 1,
    "MAXINDEX": 1,
    "MININDEX": 1,
    "MINMAX": 1,
    "MINMAXINDEX": 1,

    # Parabolic SAR
    "SAR": 1,
    "SAREXT": 1,

    # Hilbert / Ehlers family
    "HT_DCPERIOD": 1,
    "HT_DCPHASE": 1,
    "HT_PHASOR": 1,
    "HT_SINE": 1,
    "HT_TRENDLINE": 1,
    "HT_TRENDMODE": 1,

    # Candlestick patterns (all O/H/L/C from one DF)
    "CDL2CROWS": 1,
    "CDL3BLACKCROWS": 1,
    "CDL3INSIDE": 1,
    "CDL3LINESTRIKE": 1,
    "CDL3STARSINSOUTH": 1,
    "CDL3WHITESOLDIERS": 1,
    "CDLABANDONEDBABY": 1,
    "CDLADVANCEBLOCK": 1,
    "CDLBELTHOLD": 1,
    "CDLBREAKAWAY": 1,
    "CDLCLOSINGMARUBOZU": 1,
    "CDLCONCEALBABYSWALL": 1,
    "CDLCOUNTERATTACK": 1,
    "CDLDARKCLOUDCOVER": 1,
    "CDLDOJI": 1,
    "CDLDOJISTAR": 1,
    "CDLDRAGONFLYDOJI": 1,
    "CDLENGULFING": 1,
    "CDLEVENINGDOJISTAR": 1,
    "CDLEVENINGSTAR": 1,
    "CDLGAPSIDESIDEWHITE": 1,
    "CDLGRAVESTONEDOJI": 1,
    "CDLHAMMER": 1,
    "CDLHANGINGMAN": 1,
    "CDLHARAMI": 1,
    "CDLHARAMICROSS": 1,
    "CDLHIGHWAVE": 1,
    "CDLHIKKAKE": 1,
    "CDLHIKKAKEMOD": 1,
    "CDLHOMINGPIGEON": 1,
    "CDLIDENTICAL3CROWS": 1,
    "CDLINNECK": 1,
    "CDLINVERTEDHAMMER": 1,
    "CDLKICKING": 1,
    "CDLKICKINGBYLENGTH": 1,
    "CDLLADDERBOTTOM": 1,
    "CDLLONGLEGGEDDOJI": 1,
    "CDLLONGLINE": 1,
    "CDLMARUBOZU": 1,
    "CDLMATCHINGLOW": 1,
    "CDLMATHOLD": 1,
    "CDLMORNINGDOJISTAR": 1,
    "CDLMORNINGSTAR": 1,
    "CDLONNECK": 1,
    "CDLPIERCING": 1,
    "CDLRICKSHAWMAN": 1,
    "CDLRISEFALL3METHODS": 1,
    "CDLSEPARATINGLINES": 1,
    "CDLSHOOTINGSTAR": 1,
    "CDLSHORTLINE": 1,
    "CDLSPINNINGTOP": 1,
    "CDLSTALLEDPATTERN": 1,
    "CDLSTICKSANDWICH": 1,
    "CDLTAKURI": 1,
    "CDLTASUKIGAP": 1,
    "CDLTHRUSTING": 1,
    "CDLTRISTAR": 1,
    "CDLUNIQUE3RIVER": 1,
    "CDLUPSIDEGAP2CROWS": 1,
    "CDLXSIDEGAP3METHODS": 1,
}

# ---- Ideal single period per indicator (US equities) ----
# Uses your predefined variables: daily, weekly, monthly, annually,
# intraday_1min, intraday_5min, intraday_10min, intraday_30min, intraday_1hour

strategy_ideal_periods = {
    # Volume‑based (stable signals on EOD)
    "chaikin_ad_line": daily,
    "ADOSC": daily,
    "OBV": daily,
    "MFI": daily,

    # Trend / Directional (trend strength reads cleaner on EOD)
    "ADX": daily,
    "ADXR": daily,
    "DX": daily,
    "MINUS_DI": daily,
    "PLUS_DI": daily,
    "MINUS_DM": daily,
    "PLUS_DM": daily,
    "AROON": daily,
    "AROONOSC": daily,

    # Parabolic SAR (trend‑following; fewer whipsaws on EOD)
    "SAR": daily,
    "SAREXT": daily,

    # Volatility / Bands / Ranges (position sizing & swings)
    "ATR": daily,
    "NATR": daily,
    "TRANGE": daily,
    "BBANDS": daily,

    # MAs and MA‑derived (swing‑trade baseline)
    "SMA": daily,
    "EMA": daily,
    "WMA": daily,
    "DEMA": daily,
    "TEMA": daily,
    "TRIMA": daily,
    "KAMA": daily,
    "T3": daily,
    "MA": daily,
    "MACD": daily,
    "MACDEXT": daily,
    "MACDFIX": daily,
    "TRIX": daily,
    "MAMA": daily,
    "MIDPOINT": daily,

    # Momentum oscillators
    "RSI": daily,               # robust OB/OS on EOD
    "CMO": daily,
    "CCI": daily,
    "MOM": daily,
    "ROC": daily,
    "ROCP": daily,
    "ROCR": daily,
    "ROCR100": daily,
    "ULTOSC": daily,
    "WILLR": daily,
    "BOP": daily,

    # Stochastic family (timing entry; 1h balances noise vs responsiveness)
    "STOCH": intraday_1hour,
    "STOCHF": intraday_1hour,
    "STOCHRSI": intraday_1hour,

    # Price transforms (feed for other logic)
    "AVGPRICE": daily,
    "MEDPRICE": daily,
    "MIDPRICE": daily,
    "TYPPRICE": daily,
    "WCLPRICE": daily,

    # Statistics / regressions (cross‑section & risk models typically EOD)
    "BETA": daily,
    "CORREL": daily,
    "LINEARREG": daily,
    "LINEARREG_ANGLE": daily,
    "LINEARREG_INTERCEPT": daily,
    "LINEARREG_SLOPE": daily,
    "STDDEV": daily,
    "VAR": daily,
    "TSF": daily,
    "SUM": daily,
    "MAX": daily,
    "MIN": daily,
    "MAXINDEX": daily,
    "MININDEX": daily,
    "MINMAX": daily,
    "MINMAXINDEX": daily,

    # Hilbert / Ehlers cycle tools (avoid ultra‑short cycles; 30m is a good compromise)
    "HT_DCPERIOD": intraday_30min,
    "HT_DCPHASE": intraday_30min,
    "HT_PHASOR": intraday_30min,
    "HT_SINE": intraday_30min,
    "HT_TRENDLINE": intraday_30min,
    "HT_TRENDMODE": intraday_30min,

    # Candlestick patterns (best reliability on EOD)
    "CDL2CROWS": daily,
    "CDL3BLACKCROWS": daily,
    "CDL3INSIDE": daily,
    "CDL3LINESTRIKE": daily,
    "CDL3STARSINSOUTH": daily,
    "CDL3WHITESOLDIERS": daily,
    "CDLABANDONEDBABY": daily,
    "CDLADVANCEBLOCK": daily,
    "CDLBELTHOLD": daily,
    "CDLBREAKAWAY": daily,
    "CDLCLOSINGMARUBOZU": daily,
    "CDLCONCEALBABYSWALL": daily,
    "CDLCOUNTERATTACK": daily,
    "CDLDARKCLOUDCOVER": daily,
    "CDLDOJI": daily,
    "CDLDOJISTAR": daily,
    "CDLDRAGONFLYDOJI": daily,
    "CDLENGULFING": daily,
    "CDLEVENINGDOJISTAR": daily,
    "CDLEVENINGSTAR": daily,
    "CDLGAPSIDESIDEWHITE": daily,
    "CDLGRAVESTONEDOJI": daily,
    "CDLHAMMER": daily,
    "CDLHANGINGMAN": daily,
    "CDLHARAMI": daily,
    "CDLHARAMICROSS": daily,
    "CDLHIGHWAVE": daily,
    "CDLHIKKAKE": daily,
    "CDLHIKKAKEMOD": daily,
    "CDLHOMINGPIGEON": daily,
    "CDLIDENTICAL3CROWS": daily,
    "CDLINNECK": daily,
    "CDLINVERTEDHAMMER": daily,
    "CDLKICKING": daily,
    "CDLKICKINGBYLENGTH": daily,
    "CDLLADDERBOTTOM": daily,
    "CDLLONGLEGGEDDOJI": daily,
    "CDLLONGLINE": daily,
    "CDLMARUBOZU": daily,
    "CDLMATCHINGLOW": daily,
    "CDLMATHOLD": daily,
    "CDLMORNINGDOJISTAR": daily,
    "CDLMORNINGSTAR": daily,
    "CDLONNECK": daily,
    "CDLPIERCING": daily,
    "CDLRICKSHAWMAN": daily,
    "CDLRISEFALL3METHODS": daily,
    "CDLSEPARATINGLINES": daily,
    "CDLSHOOTINGSTAR": daily,
    "CDLSHORTLINE": daily,
    "CDLSPINNINGTOP": daily,
    "CDLSTALLEDPATTERN": daily,
    "CDLSTICKSANDWICH": daily,
    "CDLTAKURI": daily,
    "CDLTASUKIGAP": daily,
    "CDLTHRUSTING": daily,
    "CDLTRISTAR": daily,
    "CDLUNIQUE3RIVER": daily,
    "CDLUPSIDEGAP2CROWS": daily,
    "CDLXSIDEGAP3METHODS": daily,
}


from strategies.talib_strategy import AD_Strategy

# populate with classes of strategies that we want as agents to run
strategies = [AD_Strategy]
